export const GET_ALL_NACIONAL = 'GET_ALL_NACIONAL';
export const GET_ALL_DEPARTAMENTOS = 'GET_ALL_DEPARTAMENTOS';
export const GET_ALL_CAPITALES = 'GET_ALL_CAPITALES';
export const POST_ERROR = 'POST_ERROR';